### ISSUE TITLE
mcc p-value is not correct for negative estimate

### ISSUE THREAD

**Issue by spocks** [bhklab/CoreGx#118]
For negative values of mcc estimate, function is returning wrong p-values

```
x <- factor(c("A", "B", "A", "B", "A", "A"))
CoreGx::mcc(x,x)

#$estimate
#[1] 1
#$p.value
#[1] 0.000999001


y <- factor(x, levels = c("B","A"))
CoreGx::mcc(x, y)

#$estimate
#[1] -1
#$p.value
#[1] 0.941
```

**Comment by p-smirnov** [comment]
No one said it was a two sided p value :smile: 

Fill fix with the standard alternative parameter

**Comment by bhaibeka** [comment]
Should we make it two-sided by default?

**Comment by spocks** [comment]
yes should be two-sided by default just like Pearson etc.

**Comment by p-smirnov** [comment]
22a4502d65f9bc5976a877ed0f0edc3b5dd1ab88 is not two sided (missing a factor of 2)

**Comment by p-smirnov** [comment]
09e5658 adds alternative par, defaults to two sided. 

good catch on the >= @spocks
